# Generated by Django 3.0 on 2020-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField()),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email', models.CharField(max_length=60)),
                ('ph_no', models.PositiveIntegerField()),
            ],
        ),
    ]
